version: "3.8"
services:
  rbtr-public:
    build:
        context: ./
        dockerfile: rbtr-public-Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  rbtr-private:
    build: 
        context: ./
        dockerfile: rbtr-private-Dockerfile
    ports:
      - "35000:35000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
