version: "3.8"
services:
  rbtr-public:
    build:
        context: .
        dockerfile: rbtr-public-Dockerfile
    ports:
      - "5000:5000"
  rbtr-private:
    build: 
        context: .
        dockerfile: rbtr-private-Dockerfile
  nmc-id:
    build: 
        context: .
        dockerfile: nmc-id-Dockerfile
    ports:
      - "18420:18420"
  redis:
    image: redis
  electrs:
    image: bitcoindevkit/electrs
    ports:
      - "18443-18444:18443-18444"
      - "60401:60401"
volumes:
  logvolume01: {}
