version: "3.8"
services:
  rbtr-public:
    build:
        context: .
        dockerfile: rbtr-public-Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
  rbtr-private:
    build: 
        context: .
        dockerfile: rbtr-private-Dockerfile
    ports:
      - "35000:35000"
    volumes:
      - .:/code
      - logvolume01:/var/log
  redis:
    image: redis
  electrs:
    image: bitcoindevkit/electrs
    ports:
      - "18443-18444:18443-18444"
      - "60401:60401"
volumes:
  logvolume01: {}
