[package]
name = "tglib"
version = "0.1.0"
authors = ["dk <dk@dk.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = { version = "0.25", features = ["use-serde"] }
nom = "5.1.2"
byteorder = "1.3.4"
