version: "3.8"
services:
  ump-publisher:
    build:
        context: .
        dockerfile: publisher-Dockerfile
    ports:
      - "60600:60600"
  ump-signer:
    build: 
        context: .
        dockerfile: signer-Dockerfile
  ump-web:
    build: 
        context: .
        dockerfile: web-Dockerfile
    ports:
      - "3000:3000"
volumes:
  logvolume01: {}
