[package]
name = "player-wallet"
version = "0.1.0"
authors = ["dk <dk@dk.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.21.0"
secp256k1 = { version = "0.17.2", features = ["rand-std", "serde"] }
hex = "0.4.2"
byteorder = "1.3.4"
bdk = { git = "https://github.com/bitcoindevkit/bdk" }
tglib = { path = "../tglib" }
serde = { version = "1.0", features = ["derive"] }
clap = "2"
log = "0.4"
chrono = "0.4"
fern = "0.6"
rustyline = "6.2.0"
